version: '3'

services:
  backend:
    build: ./acwatts_backend
    ports:
      - "8000:8000"
    volumes:
      - ./acwatts_backend:/code
    environment:
      - DATABASE_URL=postgres://acw:teeza123@db:5432/acwatts_db

  frontend:
    build: ./acwatts_frontend
    ports:
      - "4173:4173"

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: acwatts_db
      POSTGRES_USER: acw
      POSTGRES_PASSWORD: teeza123
    volumes:
      - ./pgdata:/var/lib/postgresql/data
