version: '3'

services:
  backend:
    build:
      context: ./acwatts_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./acwatts_backend:/app
    depends_on:
      - database
    environment:
      - MYSQL_DATABASE=acm_db
      - MYSQL_USER=acmandi
      - MYSQL_PASSWORD=acmandi123
      - MYSQL_HOST=database
      - MYSQL_PORT=3306

  frontend:
    build:
      context: ./acwatts_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./acwatts_frontend:/app/local
    depends_on:
      - backend

  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: acm_db
      MYSQL_USER: acmandi
      MYSQL_PASSWORD: acmandi123
      MYSQL_ROOT_PASSWORD: teeza123
    ports:
      - "3306:3306"
