# Generated by Django 5.0.5 on 2024-05-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.CharField(max_length=39)),
                ('hits', models.PositiveIntegerField(default=0)),
                ('unique_visits', models.PositiveIntegerField(default=0)),
                ('last_visit', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
